meta:
  engine: 4.2.1
  name: prinia
  version: 0.1
  author: keval
  
units:
  # Parameters
  # ==========
  capx: 18        # Key cap size horizontal
  capy: 18        # Key cap size vertical
  kx: capx + 1    # Key spacing horizontal
  ky: capy + 1    # Key spacing vertical
  pinky_stagger: 0.955ky+0.026
  pinky_splay: 5  # Degrees of splay between pinky and ring columns
  pinky_adj: -9.1   # Adjustment to compensate for splay spacing
  ring_splay: 3
  ring_adj: -9.5
  tucky_splay: -10
  reachy_splay: -10

  # Constants
  # =========
  pro_x: 17.78
  pro_y: 33.08
  visual_x: 1     # Visual representation of keycaps horizontal
  visual_y: 1     # Visual representation of keycaps vertical
  sf: 16          # Switch footprint (square)

points:
  zones.matrix:
    anchor.shift: [150, -125]
    rotate: pinky_splay + ring_splay
    key:
      width: capx
      height: capy
      spread: kx
      padding: ky
      autobind: 0          
    rows:
      bottom:
      home:
      top:
    columns.pinky:
      rows:
        bottom.skip: true
        home:
          bind: [0, 0.6kx, 0, 0]   
          column_net: P21
        top:
          bind: [0, 0.5kx, 0.3ky, 0]   

          column_net: P20
    columns.ring:
      key:
        stagger: pinky_stagger
        splay: -pinky_splay
        origin: [0, pinky_adj]
      rows:
        bottom:
          bind: [0, 0, 0, 0.5kx]         
          column_net: P15
        home:
          bind: [0, 0, 0.5ky, 0]     
          column_net: P18
        top:
          bind: [0, 0.5kx, 0.5ky, 0]     
          column_net: P19
    columns.middle:
      key:
        stagger: 0.25ky
        splay: -ring_splay
        origin: [0, ring_adj]
      rows:
        bottom:
          bind: [0.5ky, 0.5kx, 0, 0.5kx]   
          column_net: P10
        home:
          bind: [0, 0.5kx, 0, 0]           
          column_net: P16
        top:
          # bind: [-1, 1.5, 0.5ky, 1.5]           
          bind: [-1, 0, 0.5ky, 0]           
          column_net: P14
    columns.index:
      key:
        stagger: -0.25ky
      rows:
        bottom:
          bind: [0.5ky, 0.5kx, 0, 0]     
          column_net: P3
        home:
          column_net: P4
        top:
          bind: [0, 1, 0.5ky, 0.5kx]     
          column_net: P5
    columns.inner:
      key:
        stagger: -0.5ky
      rows:
        bottom.skip: true
        home:
          bind: [0, 0, 1.7ky, 0]   
          column_net: P7
        top:
          bind: [0.5ky, 0, 0.5ky, 0.5kx]       
          column_net: P6

  zones.thumb:
    anchor:
      ref: matrix_index_bottom
      shift: [0.9kx, -26.75]
    key:
    columns:
      tucky:
        key:
          splay: tucky_splay
          bind: [0.1ky, 0.1kx, 0, 0.5kx]   
          column_net: P9
      reachy:
        key:
          spread: 1.08kx-0.015
          stagger: -0.086ky-0.16
          splay: reachy_splay
          bind: [0.1ky, 0, 0, 0.4kx]       
          column_net: P8
          rotate: 0 #-90
  zones.single_thumb:
    anchor:
      aggregate.parts: [thumb_tucky, thumb_reachy]
      shift: [0,0.5]
    key:
      column_net: P8
  # zones.mouse_bite_bot:
  #   anchor: 
  #     ref: matrix_pinky_top
  #     shift: [-2,-11.25]
  #   key:
  #     width: 0.6
  #     height: 0.6
  #     spread: 1
  #   columns:
  #     1:
  #     2: 
  #     3:
  #     4:
  #     5:
  # zones.mouse_bite_right: 
  #   anchor: 
  #     ref: matrix_ring_home
  #     shift: [-7.75,-2]
  #   key:
  #     width: 0.6
  #     height: 0.6
  #     padding: 1
  #   rows:
  #     1:
  #     2: 
  #     3:
  #     4:
  #     5:
  # Components
  # ==========
  zones.mcu:
    anchor:
      ref: matrix_middle_home
      shift: [-1.47kx+0.5, -2.5ky-0.2+0.4]
      rotate: 90
    key:
      width: pro_x
      height: pro_y
  zones.reset_switch_tht:
    anchor:
      - ref: matrix_inner_top
        # rotate: 90
        shift: [0,13.5]
    key:
      height: 3.5
      width: 6
  zones.reset_switch_smd:
    anchor:
      - ref: matrix_inner_home
        shift: [16.5-0.15,-24]        
        rotate: 270
    key:
      height: 3.5
      width: 6      
  zones.power_switch:
    anchor:
      - ref: matrix_inner_home
        shift: [16.5-0.35,-15]
        # rotate: 180
    key:
      height: 6
      width: 3.5
  zones.battery:
    anchor:
      ref: matrix_middle_bottom
      shift: [8-0.6,-27+0.4]
    key: 
      height: 20.5
      width: 32
  zones.battery_connector:
    anchor:
      ref: matrix_middle_bottom
      affect: xy
      shift: [2, -0.67ky]
    key:
      height: 3.5
      width: 6  
  # zones.hole:
  #   anchor:
  #     - ref: matrix_ring_home
  #       shift: [-8.5,5.5]
    # anchor:
    #   - ref: matrix_pinky_home
    #     affect: y
    #     shift: [0,8.5+3.5]
    #   - ref: matrix_ring_home
    #     affect: x
    #     shift: [-8,0]  
    # key: 
    #   height: 3
    #   width: 3    

# Mounting holes            
  zones.mounting_hole_1:
    anchor:
      ref: single_thumb
      shift: [-4,12]
    key:
      width: 4
      height: 4
  zones.mounting_hole_2:
    anchor:
      aggregate.parts: [matrix_ring_top, matrix_pinky_top]
      shift: [-1,3]
    key:
      width: 4
      height: 4  
  # zones.mounting_hole_3:
  #   anchor:
  #     aggregate.parts: [matrix_ring_bottom, matrix_pinky_home]
  #     shift: [0,0]
  #   key:
  #     width: 4
  #     height: 4    
  zones.mounting_hole_4:
    anchor:
      ref: matrix_inner_top
      shift: [-7, 12]
    key:
      width: 4
      height: 4      
outlines:
  key_outline:
    - what: rectangle
      bound: true
      size: sf
      where: 
        - /matrix._*/
        - /thumb._*/ 
  _panel_cut: # for 102*102mm outline
    - what: rectangle # top
      size: [150, 102]                   
      where: matrix_middle_bottom
      adjust:
        shift: [5,-1.3+103]
        rotate: 8       
    - what: rectangle # left
      size: [102, 150]                   
      where: matrix_middle_bottom
      adjust:
        shift: [5-103,-1.3]
        rotate: 8     
    - what: rectangle # right
      size: [102, 150]                   
      where: matrix_middle_bottom
      adjust:
        shift: [5+103,-1.3]
        rotate: 8  
    - what: rectangle # bot
      size: [150,102]                       
      where: matrix_middle_bottom
      adjust:
        shift: [5,-1.3-103-5]
        rotate: 8
  _mcu_pcb:
    - what: rectangle
      size: [80,30]
      where: matrix_middle_bottom
      adjust.shift: [-10,-22+-0.659]
    - what: rectangle
      size: [20,72]
      where: matrix_inner_home
      adjust.shift: [8,0.5]   
  _pinky_top:
    - what: rectangle
      size: [60,40]
      where: matrix_middle_home
      adjust.shift: [-14,2.25]

      
  # _gap_mouse_bite:
  # # Gap (mouse_bite)  
  #   - what: rectangle # gap bot
  #     size: [30,1.5]
  #     where: matrix_pinky_top
  #     adjust.shift: [-2.462-0.5+0.5,-10.5+0.25]
  #   - what: rectangle # gap right
  #     size: [1.5,45]
  #     where: matrix_ring_home
  #     adjust.shift: [-8.5-0.25,+1.695+0.5+10-0.498]
  #     fillet: 1
  # _tab_mouse_bite: 
  #   - what: rectangle # tab bot
  #     size: [4.75,5]          
  #     where: matrix_pinky_top
  #     adjust.shift: [0,-9]
  #   - what: rectangle # tab
  #     size: [5,4.75]  
  #     where: matrix_ring_home
  #     adjust.shift: [-9.5,0]
  _pcb_0: # add mcu space and subtract gap mouse bite
    - what: outline
      name: key_outline     
    - what: outline
      name: _mcu_pcb      
    # - what: outline
    #   name: _gap_mouse_bite
    #   operation: subtract
      # fillet: 1.5
  _pcb_1: # panel cut    
    - what: outline
      name: _pcb_0    
    - what: outline
      name: _panel_cut
      operation: subtract  
      fillet: 1
  pcb_outline: # add tab mouse bite
    - what: outline
      name: _pcb_1
    - what: outline
      name: _pinky_top  
      
    # - what: outline
    #   name: _tab_mouse_bite       
      fillet: 1.5  

  _battery:
    - what: rectangle
      size: [32,20.5]
      where: battery
      
pcbs:
  prinia:
    template: kicad8
    outlines:
      main:
        outline: pcb_outline # pbc_debug # pcb_outline
      panel: 
        outline: _battery
        layer: Cmts.User
    footprints:
      choc_solder_1:
        what: ceoloide/switch_choc_v1_v2
        where: /matrix_.*/
        adjust.rotate: 180
        params:
          from: "{{column_net}}"
          to: "GND"
          reversible: true
          hotswap: false
          solder: true 
          include_keycap: true
          choc_v2_support: false
      choc_solder_3:
        what: ceoloide/switch_choc_v1_v2
        where: 
          - /thumb_.*/
          - single_thumb
        adjust.rotate: 90
        params:
          from: "{{column_net}}"
          to: "GND"
          reversible: true
          hotswap: false
          solder: true 
          include_keycap: true
          choc_v2_support: false                    
      mcu:
        what: ceoloide/mcu_supermini_nrf52840
        where: mcu
        params:
          reverse_mount: true       
          reversible: true 
          only_required_jumpers: true 
          show_instructions: false          
      mounting_hole:
        what: ceoloide/mounting_hole_plated
        where: /mounting_hole/i
      filled_zone:
        what: ceoloide/utility_filled_zone          
        params:
          side: 'F&B'
          pad_clearance: 0.28
          

          corner_smoothing: 'none'
          smoothing_radius: 0
          remove_islands: 'never'
          fill_type: 'hatch'
          hatch_thickness: 0.55
          hatch_gap: 1
          hatch_smoothing_level: 1
          hatch_smoothing_value: 0.2

      jlcpcb_order_number_text:
        what: ceoloide/utility_text
        where: matrix_index_home
        params:
          text: JLCJLCJLCJLC
        adjust:
          shift: [0, u/2-22.5] 
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where: battery_connector
        adjust.rotate: 90
        params:
          reversible: true 
          include_traces: true
          trace_width: 0.4
          # include_silkscreen: true
          include_fabrication: false
          include_courtyard: false
      reset_switch_tht:
        what: ceoloide/reset_switch_tht_top
        where: reset_switch_tht
      power_switch:
        what: ceoloide/power_switch_smd_side
        where: power_switch
        params:
          reversible: true
          from: 'RAW'
          to: 'BAT_P'
      reset_switch_smd:
        what: ceoloide/reset_switch_smd_side
        where: reset_switch_smd
        params:
          designator: 'RST_S'
          reversible: true 
          include_bosses: true 
      mouse_bite:
        what: ceoloide/mounting_hole_npth
        where: /mouse_bite_.*/
        params:
          hole_size: '0.64'
          hole_drill: '0.64'